import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  hhContainer: {
    backgroundColor: "#7ba7ed",
    borderRadius: 15,
    padding: 15,
    marginBottom: 10,
    width: "70%",
    alignSelf: "center",
  },
  hhText: { textAlign: "center", fontSize: 27, fontWeight: "bold" },
  hContainer: {
    backgroundColor: "#b1c9f0",
    borderRadius: 15,
    padding: 15,
    marginBottom: 10,
    maxWidth: "70%",
    alignSelf: "center",
  },
  hText: { textAlign: "center", fontSize: 20, fontWeight: "bold" },
  bContainer: {
    backgroundColor: "#c7d7f0",
    maxWidth: "85%",
    borderRadius: 15,
    padding: 15,
    marginBottom: 10,
  },
  bText: { textAlign: "center", fontSize: 18 },
  resultsEntryContainer: {
    justifyContent: "flex-start",
    alignItems: "center",
    flexDirection: "row",
    backgroundColor: "#d1d9e3",
    borderRadius: 5,
    padding: 10,
    marginLeft: 10,
    marginRight: 10,
    maxWidth: "100%",
    marginBottom: 8,
  },
  resultsEntryContainerSummary: {
    justifyContent: "flex-start",
    alignItems: "center",
    flexDirection: "row",
    backgroundColor: "#d1d9e3",
    borderRadius: 5,
    padding: 10,
    marginLeft: 10,
    marginRight: 10,
    maxWidth: "100%",
    marginBottom: 23,
    marginTop: 15,
  },
  resultsEntryDataContainer: {
    paddingLeft: 10,
    flex: 1,
  },
  resultsEntryDataContainerSummary: {
    paddingLeft: 10,
    flex: 1,
    paddingRight: 0,
    paddingTop: 5,
    paddingBottom: 5,
  },
  resultsEntryDataText: {
    textAlign: "right",
    fontSize: 18,
  },
  resultsEntryLabelContainer: {
    paddingRight: 10,
    width: 120,
  },
  resultsEntryDataTextSummary: {
    textAlign: "auto",
    fontSize: 18,
  },
  resultsEntryLabelText: {
    textAlign: "left",
    fontSize: 18,
    fontWeight: 700,
  },
  rightButton: {
    position: "absolute",
    right: 16,
    top: 5,
  },
  leftButton: {
    position: "absolute",
    left: 16,
    top: 5,
  },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    height: 60,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: "bold",
    top: -7,
  },
  homeContainer: {
    flex: 1,
    backgroundColor: "#b1c9f0",
    alignItems: "center",
  },
  homeTitle: {
    color: "#0c3b87",
    fontWeight: "bold",
    fontFamily: "AmericanTypewriter-Bold",
    fontSize: 50,
    marginTop: 10,
  },
  homeButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    paddingTop: 40,
    paddingBottom: 50,
    alignItems: "center",
    width: "100%",
  },
});
